// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCFDzAxUospdQIfLRNuEpvEP2Xw0i8XVI',
    appId: '1:1075057207551:web:162c036a0ea92c6ce704ca',
    messagingSenderId: '1075057207551',
    projectId: 'finproject-9c5c6',
    authDomain: 'finproject-9c5c6.firebaseapp.com',
    storageBucket: 'finproject-9c5c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3aZjic5WhKIr6sONruKauIhVlIrGQto',
    appId: '1:1075057207551:android:2941ebe9bee18eabe704ca',
    messagingSenderId: '1075057207551',
    projectId: 'finproject-9c5c6',
    storageBucket: 'finproject-9c5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_U-QOCDuoKhd92iv3tUanyGkWnnOHnKc',
    appId: '1:1075057207551:ios:1652ca8287e2b0a4e704ca',
    messagingSenderId: '1075057207551',
    projectId: 'finproject-9c5c6',
    storageBucket: 'finproject-9c5c6.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_U-QOCDuoKhd92iv3tUanyGkWnnOHnKc',
    appId: '1:1075057207551:ios:1652ca8287e2b0a4e704ca',
    messagingSenderId: '1075057207551',
    projectId: 'finproject-9c5c6',
    storageBucket: 'finproject-9c5c6.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCFDzAxUospdQIfLRNuEpvEP2Xw0i8XVI',
    appId: '1:1075057207551:web:a603052bf0ccee16e704ca',
    messagingSenderId: '1075057207551',
    projectId: 'finproject-9c5c6',
    authDomain: 'finproject-9c5c6.firebaseapp.com',
    storageBucket: 'finproject-9c5c6.appspot.com',
  );
}
